### PR TITLE
Set IsBare true if migrated repo is empty

### LINKED ISSUE #1588: 500 after migrating repo from local bare repo
I migrated a repo using its local file path successfully, but when I go to the page I get a 500 error:

    [Macaron] Started GET /org/repo for 127.0.0.1
    2015/09/06 11:43:46 [...s/middleware/repo.go:361 func·009()] [E] GetBranches:
    [Macaron] Completed /org/repo 500 Internal Server Error in 16.84093ms

What could be the reason?

### PR DESCRIPTION
**Pull request by siadat**
Set `repo.IsBare` true if the migrated repository is empty.

Closes #1588

### CODE REVIEW

File: models/repo.go [hunk 1]
```diff
@@ -470,6 +470,12 @@ func MigrateRepository(u *User, name, desc string, private, mirror bool, url str
 		return repo, fmt.Errorf("create update hook: %v", err)
 	}
 
+	// Check if repository is empty.
+	_, _, err = com.ExecCmdDir(repoPath, "git", "rev-parse", "--verify", "--quiet", "HEAD")
```
Comment (Unknwon) [inline models/repo.go]: Will there be an error if it's not empty?

Comment (siadat) [inline models/repo.go]: Yes, the exit status will be non-zero if the repository is empty!

Comment (Unknwon) [inline models/repo.go]: Thanks for following up! And what about stderr? Will there just be an error and no stdout or stderr if it's empty?

Comment (Unknwon) [inline models/repo.go]: How about use `git log` to test? 

It always complains error `fatal: bad default revision 'HEAD'` for empty repository, which more precise in case there is another real error happens.

Comment (siadat) [inline models/repo.go]: stderr is silenced by `--quiet`. I running `git log` on a repository with thousands of commits might not be a good idea because it might take a long time. This approach only finds the commit that is referenced by `HEAD`, the exit status will be 0 (a commit found) or non-zero (no commit found).

Comment (Unknwon) [inline models/repo.go]: Hmm... that's easy, just use `git log -1`, so it only finds latest 1 commit and stops.

Comment (Unknwon) [inline models/repo.go]: OK, so if you don't use `--quite`, you can check error string for `fatal: Needed a single revision`.

Comment (siadat) [inline models/repo.go]: So, we these alternatives:

    git log -1
    fatal: bad default revision 'HEAD'

    git rev-parse --verify HEAD
    fatal: Needed a single revision

If you think checking stderr is more reliable than checking err, I could update the commit to do something like this instead:

    _, stderr, err := com.ExecCmdDir(repoPath, "git", "log", "-1")
    if err != nil && strings.Contains(stderr, "fatal:") { ... }

Let me know what you think.

Comment (Unknwon) [inline models/repo.go]:
```go
_, stderr, err := com.ExecCmdDir(repoPath, "git", "log", "-1")
if err != nil && strings.Contains(stderr, "fatal: bad default revision 'HEAD'") { ... }
```

would be prefect!

Comment (siadat) [inline models/repo.go]: :+1:

Comment (siadat) [inline models/repo.go]: @Unknwon commit updated!

**Comment by Unknwon** [comment]
Great! Can you confirm that this PR actually fixes your problem?

**Comment by siadat** [comment]
Yup, I just tested it again by migrating an empty repository, and it showed the expected bare.tmpl page instead of the old 500 page.

For empty repositories already migrated, they should either be deleted and re-migrated, or manually set their `is_bare = 1` in the database.

**Comment by Unknwon** [comment]
Thank you very much!

**Comment by siadat** [comment]
Thank you! :tada:
