### PR TITLE
Fix #3154

### LINKED ISSUE #3154: Duplicate issue race condition
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

For bug reports, please give the relevant info:

- Gogs version (or commit ref):0.9.13.0318
- Git version: 2.7.4
- Operating system: NixOS (Linux)
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io: (Trying to, but since it's a race condition, it's hard)
  - [ ] Yes (provide example URL)
  - [ ] No
  - [ ] Not relevant
- Log gist:

- MySQL table : 

```
pull_request :

+----+------+--------+----------+-------+--------------+--------------+----------------+-------------+-------------+------------------------------------------+------------+------------------------------------------+---------------------+-----------+--------------+
| id | type | status | issue_id | index | head_repo_id | base_repo_id | head_user_name | head_branch | base_branch | merge_base                               | has_merged | merged_commit_id                         | merged              | merger_id | merged_unix  |
+----+------+--------+----------+-------+--------------+--------------+----------------+-------------+-------------+------------------------------------------+------------+------------------------------------------+---------------------+-----------+--------------+
| 19 |    0 |      2 |       94 |    17 |           29 |           25 | edelangh       | master      | master      | 52737574ec6777c51339cc61a78bae207efc5316 |          1 | 3e1619ed61cacc43c0eeb8e809a7ca7efe06ac1a | NULL                |         9 |   1464689348 |
| 20 |    0 |      2 |       95 |    17 |           29 |           25 | edelangh       | master      | master      | 3e1619ed61cacc43c0eeb8e809a7ca7efe06ac1a |          0 |                                          | NULL                |         0 | -62135596800 |
+----+------+--------+----------+-------+--------------+--------------+----------------+-------------+-------------+------------------------------------------+------------+------------------------------------------+---------------------+-----------+--------------+

issue :
+----+---------+-------+------------------------------------------------------------------------------------------------+-----------+--------------+-------------+---------+-----------+----------+--------------+---------------------+---------------------+---------------------+---------------+--------------+--------------+
| id | repo_id | index | name                                                                                           | poster_id | milestone_id | assignee_id | is_pull | is_closed | priority | num_comments | deadline            | created             | updated             | deadline_unix | created_unix | updated_unix |
+----+---------+-------+------------------------------------------------------------------------------------------------+-----------+--------------+-------------+---------+-----------+----------+--------------+---------------------+---------------------+---------------------+---------------+--------------+--------------+
| 94 |      25 |    17 | Use new bandeau component and some css                                                         |        12 |            0 |           0 |       1 |         1 |        0 |            0 | NULL                | NULL                | NULL                |             0 |   1464637690 |   1464637690 |
| 95 |      25 |    17 | Use new bandeau component and some css                                                         |        12 |            0 |           0 |       1 |         0 |        0 |            0 | NULL                | NULL                | NULL                |             0 |   1464637690 |   1464637690 |
+----+---------+-------+------------------------------------------------------------------------------------------------+-----------+--------------+-------------+---------+-----------+----------+--------------+---------------------+---------------------+---------------------+---------------+--------------+--------------+
```

## Description

It seems like it's possible, through a race condition, to create two issues with the same ID. This confuses gogs, as it shows the PR as opened and closed at the same time, and refuses to merge it. 

It might be a good idea to enforce a UNIQUE constraint on (RepoID, Index) in models/issue.go. That would at least prevent the database from corrupting itself.

I fixed my issue temporarely by DELETING the duplicated issue/PR manually from the database.

### PR DESCRIPTION
**Pull request by roblabla**
See #3154 for more information.

Please, make sure you are targeting the `develop` branch!

More instructions about contributing with Gogs code can be found here:
https://github.com/gogits/gogs/wiki/Contributing-Code

### CODE REVIEW

File: models/issue.go [hunk 1]
```diff
@@ -33,8 +33,8 @@ var (
 // Issue represents an issue or pull request of repository.
 type Issue struct {
 	ID              int64 `xorm:"pk autoincr"`
-	RepoID          int64 `xorm:"INDEX"`
-	Index           int64 // Index in one repository.
+	RepoID          int64 `xorm:"INDEX unique(repoissue)"`
```
Comment (Unknwon) [inline models/issue.go]: I think it would be better to call it `repo_index`?

**Comment by roblabla** [comment]
Like this ?

**Comment by Unknwon** [comment]
Yes, thanks. Waiting CI.
