### PR TITLE
Fix #3315: Release dont use tag creation date

### LINKED ISSUE #3315: Release dont use tag creation date
We DO NOT take questions or config/deploy problems on GitHub, please use our forum: https://discuss.gogs.io

Please take a moment to search that an issue doesn't already exist.

**For bug reports, please give the relevant info:**

- *Gogs version (or commit ref):* 0.9.48
- *Git version:* 1.8.3.1
- *Operating system:* Linux CentOS 7 64bit
- *Database:* SQLite
- *Can you reproduce the bug at http://try.gogs.io:* Yes --> https://try.gogs.io/zero-x-baadf00d/psychic-soul/releases (few hour ago)  and https://try.gogs.io/zero-x-baadf00d/psychic-soul/src/release/1.3.1  (6 months ago)

## Description

Release must take the linked tag creation date (like Github)

### PR DESCRIPTION
**Pull request by 0xbaadf00d**
Like Github, release note now using the tag creation date rather than the web release note creation date (Issue #3315). If tag does not exist yet, last commit on selected branch will be used.

### CODE REVIEW

File: models/release.go [hunk 1]
```diff
@@ -39,9 +39,12 @@ type Release struct {
 }
 
 func (r *Release) BeforeInsert() {
-	r.CreatedUnix = time.Now().Unix()
+	if r.CreatedUnix == 0 {
+                r.CreatedUnix = time.Now().Unix()
+	}
 }
 
+
```
Comment (Unknwon) [inline models/release.go]: >All .go files must be formatted with gofmt (most of Go editors should be already possible to format on save).

File: routers/repo/release.go [hunk 2]
```diff
@@ -167,6 +168,17 @@ func NewReleasePost(ctx *context.Context, form auth.NewReleaseForm) {
 		return
 	}
 
+	tagCreationDate := time.Now()
```
Comment (Unknwon) [inline routers/repo/release.go]: You can store a `int64` type variable here by `var tagCreatedUnix int64`, so it defaults to `0`.

File: routers/repo/release.go [hunk 3]
```diff
@@ -190,6 +202,8 @@ func NewReleasePost(ctx *context.Context, form auth.NewReleaseForm) {
 		Note:         form.Content,
 		IsDraft:      len(form.Draft) > 0,
 		IsPrerelease: form.Prerelease,
+		Created:      tagCreationDate,
+		CreatedUnix:  tagCreationDate.Unix(),
```
Comment (Unknwon) [inline routers/repo/release.go]: And here you only need to take care of `CreatedUnix`.

**Comment by 0xbaadf00d** [comment]
Thanks for your replies and tips. I will do modifications.

File: models/release.go (hunk 1 above)
Comment (Unknwon) [inline models/release.go]: Didn't fix this.

File: routers/repo/release.go [hunk 4]
```diff
@@ -260,6 +270,14 @@ func EditReleasePost(ctx *context.Context, form auth.EditReleaseForm) {
 		return
 	}
 
+	tag, err := ctx.Repo.GitRepo.GetTag(rel.TagName)
```
Comment (Unknwon) [inline routers/repo/release.go]: You didn't answer the reason why we need this.

Comment (0xbaadf00d) [inline routers/repo/release.go]: After doing more tests, you are right, this block is not necessary on `EditReleasePost` function. I will remove this today.

**Comment by Unknwon** [comment]
One fix is leaking.

**Comment by 0xbaadf00d** [comment]
gofmt is now applied to all modified files (_models/release.go_ and _routers/repo/release.go_)

**Comment by Unknwon** [comment]
Thanks!
