### PR TITLE
Fix #3437: Cannot connect to PostgreSQL via IPv6 address

### LINKED ISSUE #3437: Cannot connect to PostgreSQL via IPv6 address
Directive `HOST` in section `[database]` of `app.ini` doesn't support IPv6 addresses which makes Gogs fail, at least when PostgreSQL is used.

When IPv6 addresses get stated without brackets `gogs.log` reads
> [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: dial tcp 0.0.7.211:74: connect: invalid argument

When brackets are used there are messages like this
> [...s/routers/install.go:71 GlobalInit()] [E] Fail to initialize ORM engine: Fail to connect to database: parse postgres://\<user\>:\<password\>@[fd99:aaaa/gogs1?sslmode=disable: missing ']' in host

connecting to a ULA `fd99:aaaa:bbbb:...` which all in all suggest there's something wrong with the parsing of the addresses.
Both FQDNs and IPv4 addresses are accepted. The connection to the database server works flawlessly via IPv6 as can be seen by setting the hostname in `HOST` of app.ini and configuring the database server to accept corresponding IPv6 connections only.
On a side note directive `HOST_ADDR` in `[server]` accepts IPv6 addresses, too.

Seen running b756806 on Arch Linux, hence PostgreSQL 9.5.3.

### PR DESCRIPTION
**Pull request by 0xbaadf00d**
This PR add ability to handle IPv6 address with PostgreSQL (issue #3437). Now `HOST` can be filled with:

- `HOST = 127.0.0.1:5432`
- `HOST = 127.0.0.1`  // Use default port
- `HOST = [::1]`
- `HOST = [::1]:5432`
- `HOST = /tmp/pg.sock`
- `HOST = /tmp/pg.sock:5342`

_Tested on CentOS 7 with PostgreSQL 9.5_

### CODE REVIEW

File: models/models.go [hunk 1]
```diff
@@ -114,12 +114,11 @@ func getEngine() (*xorm.Engine, error) {
...
 	case "postgres":
 		host, port := "127.0.0.1", "5432"
-		fields := strings.Split(DbCfg.Host, ":")
-		if len(fields) > 0 && len(strings.TrimSpace(fields[0])) > 0 {
-			host = fields[0]
-		}
-		if len(fields) > 1 && len(strings.TrimSpace(fields[1])) > 0 {
-			port = fields[1]
+		if strings.Contains(DbCfg.Host, ":") && !strings.HasSuffix(DbCfg.Host, "]") {
+			host = DbCfg.Host[0:strings.LastIndex(DbCfg.Host, ":")]
```
Comment (Unknwon) [inline models/models.go]: 1. `0` is redundant.
2. We should save result of `strings.LastIndex(DbCfg.Host, ":")` to a variable and reuse.

Comment (0xbaadf00d) [inline models/models.go]: ok, thanks for tip.
