### PR TITLE
Fix #3743: Fix SHA and compare regex on route file [Critical]

### LINKED ISSUE #3743: Pull requests don't work if branch name is 7 characters or longer
- Gogs version (or commit ref): 0.9.99.0903, 0.9.97, 0.9.99.0915
- Git version: 2.1.3.36.g8e36a6d
- Operating system: OSX 10.11.6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [X] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [X] Yes: https://try.gogs.io/samuelson/foo/compare/product...product
  - [ ] No
  - [ ] Not relevant
- Log gist: No relevant logs
## Description

We'd like to use gogs for a Puppet control-repo. This usually means making the default branch "production" instead of "master".

It seems that any name beginning with the string "product" triggers this issue. When I use any other name for the base branch, the new Pull Request dialog shows drop down menus to select the branches.  When I use "product", it doesn't show drop down menus and only shows links to the product branch.

Attempting to track this down, I tried some protected words from the code, and the word "present" also triggered the bug.   I was able to repro with any branch name that is 7 characters or longer.

This is currently a blocker for us.

Edit: Narrowed down issue to branches 7 characters or longer

### PR DESCRIPTION
**Pull request by 0xbaadf00d**
Related to the issue #3743, this pull request fix the regex used on the route file for SHA and branches comparisons.

- A SHA hash can only contains `a b c d e f 0 1 2 3 4 5 6 7 8 9`
- A branch name could be smaller than 7 characters

### CODE REVIEW

File: cmd/web.go [hunk 1]
```diff
@@ -585,12 +585,12 @@ func runWeb(ctx *cli.Context) error {
...
 			m.Get("/commits/*", repo.RefCommits)
-			m.Get("/commit/:sha([a-z0-9]{7,40})$", repo.Diff)
+			m.Get("/commit/:sha([a-f0-9]{7,40})$", repo.Diff)
 			m.Get("/forks", repo.Forks)
 		}, context.RepoRef())
-		m.Get("/commit/:sha([a-z0-9]{7,40})\\.:ext(patch|diff)", repo.RawDiff)
+		m.Get("/commit/:sha([a-f0-9]{7,40})\\.:ext(patch|diff)", repo.RawDiff)
 
-		m.Get("/compare/:before([a-z0-9]{7,40})\\.\\.\\.:after([a-z0-9]{7,40})", repo.CompareDiff)
+		m.Get("/compare/:before([a-z0-9]{40})\\.\\.\\.:after([a-z0-9]{40})", repo.CompareDiff)
```
Comment (bkcsoft) [inline cmd/web.go]: And now I can't compare `master...develop` anymore :unamused:

Comment (0xbaadf00d) [inline cmd/web.go]: are you sure ?

http://127.0.0.1:3000/test/core/compare/master...develop

image

**Comment by samuelson** [comment]
+1

**Comment by strk** [comment]
is this also already fixed in gitea ?

**Comment by samuelson** [comment]
looks like it is: https://github.com/go-gitea/gitea/blob/master/cmd/web.go#L590

File: cmd/web.go (hunk 1 above)
Comment (bkcsoft) [inline cmd/web.go]: oh `[a-z]`, I read it as `[a-f]` :smile:

**Comment by Unknwon** [comment]
Thanks!
