### PR TITLE
[Fix] Don't display way too large files #1513

### LINKED ISSUE #1513: Gogs crash with 800MB textfile
存在一个800M的文本文件，通过git操作无问题。但是当通过网页浏览该文件，gogs会崩溃，并且没有日志记录。

### PR DESCRIPTION
**Pull request by bkcsoft**
Fixes #1513 

Obligatory screenshot: 
2016-07-11-094514_956x596_scrot

Default is set to 8MiB (which would fit all 7 Harry Potter books in a single file, with newlines and paragraphs :laughing: )

### CODE REVIEW

File: routers/repo/view.go [hunk 1]
```diff
@@ -104,20 +105,25 @@ func Home(ctx *context.Context) {
...
 				ctx.Data["IsImageFile"] = true
 			case isTextFile:
-				d, _ := ioutil.ReadAll(dataRc)
-				buf = append(buf, d...)
-				readmeExist := markdown.IsMarkdownFile(blob.Name()) || markdown.IsReadmeFile(blob.Name())
-				ctx.Data["ReadmeExist"] = readmeExist
-				if readmeExist {
-					ctx.Data["FileContent"] = string(markdown.Render(buf, path.Dir(treeLink), ctx.Repo.Repository.ComposeMetas()))
+				if blob.Size() >= setting.MaxDisplayFileSize {
+					ctx.Data["IsFileTooBig"] = true
```
Comment (Unknwon) [inline routers/repo/view.go]: `IsFileTooLarge`?

**Comment by bkcsoft** [comment]
@Unknwon Fixed :)

**Comment by Unknwon** [comment]
Thanks!
