### PR TITLE
Fix PR-webhook issue where Label-data is stale (#3486)

### LINKED ISSUE #3486: Pull request webhook action 'label_update' does not contain label information
- Gogs version (or commit ref):  0.9.83.0816
- Git version: 1.8.3.1
- Operating system: Linux
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [X] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [X] Not relevant

The current webhook implementation triggers a 'label_update' action but it seems like it currently does not contain information what was set in the update. It seems that the label information (what labels are set) is available with the next triggered webhook.

### PR DESCRIPTION
**Pull request by bkcsoft**
Fixes #3486 

Label-data is stale, so we have to fetch Issue-data again before sending it...

(Please feel free to suggest a better idea :laughing: )

### CODE REVIEW

File: models/issue.go [hunk 1]
```diff
@@ -233,9 +233,17 @@ func (i *Issue) HasLabel(labelID int64) bool {
 }
 
 func (issue *Issue) sendLabelUpdatedWebhook(doer *User) {
-	var err error
+	var (
+		new_issue *Issue
```
Comment (Unknwon) [inline models/issue.go]: Bad naming style.
